package com.example.synkora.quarter;
import org.junit.Test;

public class TampoyTest {
    @Test
    public void printMyProfile () {
        String myName = "Kayzee";
        String myPet = "Luna";
        String favFood = "Shrimp
        int age = 17;

        System.out.printIn("--- MY DIGITAL PROFILE ---");
        System.out.printIn("Hello, my name is " + myName + " ! and I am " + Age + " years old. ");
        System.out.printIn("My favorite food is " + favFood + " and I love my energetic pet named " + myPet);
    }
}
